-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgFRMbGTkqjctsapkfyVKfdus8MPJd8UCcRzzF2lJEmQagCgYIKoZIzj0DAQehRANCAAQvlhpA1WPlfruVzDrtEwuipgZjoolEZnPfeEm9W4sGG1rTS8gHtXxo9LyJqlR1n5uwEeq8HYSku+iLoUlSYkn8
-----END PRIVATE KEY-----